# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Adyen' do

  # Pods for Adyen
  pod 'NotificationBannerSwift'

  target 'AdyenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
